# This is a basic workflow to help you get started with Actions

name: BooksDataStore

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build and create dacpac job
  build_and_create_dacpac:
    # Selecting the windows-latest GitHub-hosted runner
    runs-on: windows-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # create dacpac using MSBUILD executable
      - name: create dacpac
        run: |
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe' BooksDataStore.sqlproj /p:Configuration=Release
        working-directory: ./source/BooksDataStore

      # Publish an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: BooksDataStore
          path: ${{ github.workspace }}/source/BooksDataStore/bin/Release/